import Link from "next/link";
import {ArrowUpRight,BarChart3,Bookmark,Eye,RefreshCw,Share2} from "lucide-react";
import {getAnalyticsDashboard} from "@/lib/analytics/data";
import {hasSupabaseEnv} from "@/lib/env";
const number=new Intl.NumberFormat("es-PA",{notation:"compact",maximumFractionDigits:1});const percent=(value:number)=>`${(value*100).toFixed(2)}%`;
export default async function Page(){if(!hasSupabaseEnv)return <Empty text="Configura Supabase para activar Analytics."/>;const data=await getAnalyticsDashboard();if(!data)return <Empty text="Completa Brand Memory para activar Analytics."/>;const hasPermission=data.account?.permissions?.includes("instagram_business_manage_insights");
  return <div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-[var(--line)] pb-7"><div><p className="eyebrow">Performance memo</p><h1 className="editorial-title mt-2 max-w-3xl text-5xl font-medium">Qué está conectando con tu audiencia.</h1></div><p className="max-w-sm text-sm leading-6 text-[var(--muted)]">Comparaciones basadas en alcance, guardados y compartidos. Las conclusiones ganan confianza a medida que publicas.</p></header>{!hasPermission&&<section className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-amber-50 p-5 text-amber-950"><div><p className="font-black">Reconecta Instagram para leer Insights</p><p className="mt-1 text-sm">Meta debe conceder el nuevo permiso de análisis.</p></div><Link className="button-primary" href="/api/instagram/connect"><RefreshCw size={16}/>Reconectar</Link></section>}
  <section className="mt-8 grid gap-px overflow-hidden rounded-[22px] border border-[var(--line)] bg-[var(--line)] sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Eye} label="Alcance" value={number.format(data.totals.reach)} detail={`${number.format(data.totals.views)} visualizaciones`}/><Metric icon={BarChart3} label="Engagement" value={percent(data.totals.engagementRate)} detail={`${number.format(data.totals.interactions)} interacciones`}/><Metric icon={Bookmark} label="Save rate" value={percent(data.totals.saveRate)} detail={`${number.format(data.totals.saves)} guardados`}/><Metric icon={Share2} label="Share rate" value={percent(data.totals.shareRate)} detail={`${number.format(data.totals.shares)} compartidos`}/></section>
  <section className="mt-8 grid gap-7 lg:grid-cols-[1.15fr_.85fr]"><article className="card p-6 sm:p-8"><p className="eyebrow">Señales de estrategia</p><h2 className="editorial-title mt-2 text-3xl font-semibold">Patrones, no anécdotas.</h2><div className="mt-7 grid gap-3">{data.patterns.length?data.patterns.map(pattern=><div key={`${pattern.dimension}:${pattern.dimension_value}`} className="grid gap-3 rounded-2xl border border-[var(--line)] p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><strong>{pattern.dimension_value}</strong><span className="rounded-full bg-[var(--violet-soft)] px-2 py-1 text-[10px] font-black text-[var(--violet)]">{pattern.confidence} · n={pattern.sample_size}</span></div><p className="mt-1 text-sm text-[var(--muted)]">{pattern.summary}</p></div><span className={`text-xl font-black ${Number(pattern.lift_percentage)>=0?"text-emerald-700":"text-red-700"}`}>{Number(pattern.lift_percentage)>=0?"+":""}{Number(pattern.lift_percentage).toFixed(0)}%</span></div>):<EmptyState text="Necesitamos al menos 3 publicaciones con datos para comparar tendencias fiables."/>}</div></article><article className="card p-6 sm:p-8"><p className="eyebrow">Piezas observadas</p><h2 className="editorial-title mt-2 text-3xl font-semibold">Último rendimiento.</h2><div className="mt-7 grid gap-4">{data.posts.slice(0,6).map(row=>{const post=Array.isArray(row.posts)?row.posts[0]:row.posts;const version=post&&(Array.isArray(post.post_versions)?post.post_versions[0]:post.post_versions);return <div className="border-b border-[var(--line)] pb-4 last:border-0" key={row.post_id}><div className="flex items-start justify-between gap-3"><p className="line-clamp-2 text-sm font-bold">{version?.hook||"Publicación de Instagram"}</p><ArrowUpRight size={16} className="shrink-0 text-[var(--violet)]"/></div><p className="mt-2 text-xs text-[var(--muted)]">{post?.format} · {number.format(Number(row.reach??0))} alcance · {percent(Number(row.engagement_rate??0))} engagement</p></div>})}{!data.posts.length&&<EmptyState text="Los resultados aparecerán después de sincronizar publicaciones."/>}</div></article></section><p className="mt-5 text-right text-xs text-[var(--muted)]">Última sincronización: {data.account?.last_sync_at?new Date(data.account.last_sync_at).toLocaleString("es-PA"):"pendiente"}</p></div>}
function Metric({icon:Icon,label,value,detail}:{icon:typeof Eye;label:string;value:string;detail:string}){return <div className="bg-white p-5 sm:p-6"><Icon size={18} className="text-[var(--violet)]"/><p className="mt-6 text-[10px] font-black uppercase tracking-widest text-[var(--muted)]">{label}</p><p className="editorial-title mt-1 text-4xl font-semibold">{value}</p><p className="mt-1 text-xs text-[var(--muted)]">{detail}</p></div>}
function EmptyState({text}:{text:string}){return <p className="rounded-2xl bg-black/[.035] p-5 text-sm leading-6 text-[var(--muted)]">{text}</p>}
function Empty({text}:{text:string}){return <div className="card p-8">{text}</div>}
