"use client";
import { useActionState } from "react";
import { useFormStatus } from "react-dom";
import { Save } from "lucide-react";
import { saveBrand, type BrandActionState } from "@/lib/brand/actions";
import type { BrandRecord } from "@/lib/brand/context";
const initial:BrandActionState={ok:false,message:""};
export function BrandForm({brand,enabled}:{brand:BrandRecord|null;enabled:boolean}){const[state,action]=useActionState(saveBrand,initial);return <form action={action} className="grid gap-6"><section className="card p-6 sm:p-8"><p className="eyebrow">01 · Esencia</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Nombre" name="name" required defaultValue={brand?.name}/><Field label="Website" name="website" type="url" defaultValue={brand?.website??""}/><TextField label="Qué haces" name="description" defaultValue={brand?.description}/><TextField label="Producto o servicio" name="productService" defaultValue={brand?.product_service}/></div></section><section className="card p-6 sm:p-8"><p className="eyebrow">02 · Personas y propósito</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><TextField label="Audiencia" name="audience" defaultValue={brand?.audience}/><TextField label="Objetivos" name="objectives" defaultValue={brand?.objectives}/></div></section><section className="card p-6 sm:p-8"><p className="eyebrow">03 · Voz</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><TextField label="Tono" name="tone" defaultValue={brand?.tone}/><TextField label="Personalidad" name="personality" defaultValue={brand?.personality}/><Field label="CTA habitual" name="defaultCta" defaultValue={brand?.default_cta}/><Field label="Idioma" name="language" defaultValue={brand?.language??"es"}/><TextField label="Frases permitidas (una por línea)" name="allowedPhrases" defaultValue={brand?.allowed_phrases.join("\n")}/><TextField label="Frases prohibidas (una por línea)" name="forbiddenPhrases" defaultValue={brand?.forbidden_phrases.join("\n")}/><TextField label="Reglas de hashtags" name="hashtagRules" defaultValue={brand?.hashtag_rules}/><TextField label="Reglas editoriales" name="editorialRules" defaultValue={brand?.editorial_rules}/><Field label="Zona horaria" name="timezone" defaultValue="America/Panama"/></div></section><div className="sticky bottom-4 flex items-center justify-between gap-4 rounded-2xl border border-[var(--line)] bg-white/90 p-4 shadow-xl backdrop-blur"><p aria-live="polite" className={`text-sm ${state.ok?"text-emerald-700":"text-red-700"}`}>{state.message||(!enabled?"Conecta Supabase para guardar.":"Los cambios alimentarán las futuras generaciones.")}</p><Submit disabled={!enabled}/></div></form>}
function Field({label,name,defaultValue="",type="text",required=false}:{label:string;name:string;defaultValue?:string;type?:string;required?:boolean}){return <label className="field-label">{label}<input className="field" name={name} type={type} defaultValue={defaultValue} required={required}/></label>}
function TextField({label,name,defaultValue=""}:{label:string;name:string;defaultValue?:string}){return <label className="field-label">{label}<textarea className="field min-h-28 resize-y" name={name} defaultValue={defaultValue}/></label>}
function Submit({disabled}:{disabled:boolean}){const{pending}=useFormStatus();return <button className="button-primary shrink-0" disabled={disabled||pending}><Save size={16}/>{pending?"Guardando…":"Guardar cambios"}</button>}
