"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { BarChart3, CalendarDays, Camera, CheckCircle2, FolderHeart, LayoutDashboard, Palette, PenLine, Settings2, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";
const primary=[["/overview","Overview",LayoutDashboard],["/approvals","Approvals",CheckCircle2],["/calendar","Calendar",CalendarDays],["/create","Create",PenLine],["/library","Library",FolderHeart],["/analytics","Analytics",BarChart3]] as const;
const settings=[["/settings/brand","Brand",Palette],["/settings/instagram","Instagram",Camera],["/settings/usage","Settings",Settings2]] as const;
export function Sidebar(){const pathname=usePathname();return <aside className="flex w-full shrink-0 flex-col border-b border-[var(--line)] bg-white px-4 py-4 lg:sticky lg:top-0 lg:h-screen lg:w-[236px] lg:border-b-0 lg:border-r lg:px-5 lg:py-7"><Link href="/overview" className="mb-5 flex items-center gap-3 px-2 lg:mb-10"><span className="grid size-9 place-items-center rounded-xl bg-[var(--ink)] text-white"><Sparkles size={16}/></span><div><p className="text-sm font-extrabold tracking-tight">CrealyHub</p><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-[var(--muted)]">Editorial desk</p></div></Link><nav className="flex gap-1 overflow-x-auto lg:grid" aria-label="Navegación principal">{primary.map(([h,l,I])=><NavItem key={h} href={h} label={l} active={pathname.startsWith(h)} icon={I}/>)}</nav><div className="my-6 hidden border-t border-[var(--line)] lg:block"/><nav className="hidden gap-1 lg:grid" aria-label="Configuración">{settings.map(([h,l,I])=><NavItem key={h} href={h} label={l} active={pathname.startsWith(h)} icon={I}/>)}</nav><div className="mt-auto hidden rounded-2xl bg-[var(--violet-soft)] p-4 lg:block"><p className="text-xs font-bold text-[var(--violet)]">Review mode</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Nada se publica sin tu aprobación.</p></div></aside>}
function NavItem({href,label,active,icon:Icon}:{href:string;label:string;active:boolean;icon:typeof LayoutDashboard}){return <Link href={href} className={cn("flex min-w-fit items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition-colors",active?"bg-[var(--ink)] text-white":"text-[var(--muted)] hover:bg-[var(--paper)] hover:text-[var(--ink)]")}><Icon size={17} strokeWidth={1.8}/><span>{label}</span></Link>}
