"use client";
import { useActionState,useState } from "react";
import { useFormStatus } from "react-dom";
import { Images,RectangleVertical,Sparkles,Square } from "lucide-react";
import { createContent } from "@/lib/content/actions";
import type { CreateContentState } from "@/lib/content/schema";
const initial:CreateContentState={ok:false,message:""};
const formats=[{id:"POST",label:"Post",ratio:"4:5",icon:Square,note:"Una idea, una imagen"},{id:"CAROUSEL",label:"Carrusel",ratio:"2–10",icon:Images,note:"Una historia por slides"},{id:"STORY",label:"Story",ratio:"9:16",icon:RectangleVertical,note:"Directa y vertical"}] as const;
export function CreateBrief({enabled}:{enabled:boolean}){const[state,action]=useActionState(createContent,initial);const[format,setFormat]=useState<"POST"|"STORY"|"CAROUSEL">("POST");return <form action={action} className="grid gap-6"><input type="hidden" name="format" value={format}/><section className="grid gap-3 sm:grid-cols-3">{formats.map(item=><button key={item.id} type="button" onClick={()=>setFormat(item.id)} className={`card relative min-h-40 p-5 text-left transition-all ${format===item.id?"border-[var(--violet)] bg-[var(--violet-soft)] shadow-none":"hover:-translate-y-1"}`}><item.icon size={24} className={format===item.id?"text-[var(--violet)]":"text-[var(--muted)]"}/><p className="mt-7 text-lg font-bold">{item.label}</p><p className="mt-1 text-xs text-[var(--muted)]">{item.note}</p><span className="absolute right-4 top-4 rounded-full bg-white px-2.5 py-1 text-[10px] font-extrabold">{item.ratio}</span></button>)}</section><section className="card p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="field-label">Tema <span className="font-normal text-[var(--muted)]">Opcional</span><input className="field" name="topic" placeholder="Ej. cómo elegir una buena miniatura"/></label><label className="field-label">Objetivo <span className="font-normal text-[var(--muted)]">Opcional</span><input className="field" name="objective" placeholder="Ej. educar y generar saves"/></label><label className="field-label sm:col-span-2">Instrucciones <span className="font-normal text-[var(--muted)]">Opcional</span><textarea className="field min-h-36 resize-y" name="instructions" placeholder="Dame una pieza minimalista. Si lo dejas vacío, decidiré usando tu Brand Memory."/></label><label className="field-label">Fecha deseada <span className="font-normal text-[var(--muted)]">Opcional</span><input className="field" type="datetime-local" name="scheduledAt"/></label></div></section><div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-[var(--ink)] p-4 pl-5 text-white"><div><p className="text-sm font-bold">{state.message||"El agente completará lo que dejes vacío."}</p><p className="mt-1 text-xs text-white/55">Se genera en segundo plano y siempre pasa a aprobación.</p></div><Submit disabled={!enabled}/></div></form>}
function Submit({disabled}:{disabled:boolean}){const{pending}=useFormStatus();return <button className="inline-flex min-h-[44px] items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-extrabold text-[var(--ink)] disabled:opacity-50" disabled={disabled||pending}><Sparkles size={16}/>{pending?"Encolando…":"Generar pieza"}</button>}
