"use client";
import {useActionState} from "react";
import {useFormStatus} from "react-dom";
import {ArrowRight,BrainCircuit,Sparkles} from "lucide-react";
import {chooseIdea,proposeIdeas,type ChooseIdeaState,type IdeaState,type ProposedIdea} from "@/lib/ideas/actions";
const initial:IdeaState={ok:false,message:"",ideas:[]};
export function IdeaRadar(){const[state,action,pending]=useActionState(proposeIdeas,initial);return <section className="mb-8 overflow-hidden rounded-[24px] bg-[var(--ink)] text-white"><div className="flex flex-wrap items-end justify-between gap-5 p-6 sm:p-8"><div className="max-w-2xl"><div className="flex items-center gap-2 text-[var(--mint)]"><BrainCircuit size={19}/><p className="text-[10px] font-black uppercase tracking-[.16em]">Radar editorial</p></div><h2 className="editorial-title mt-3 text-4xl font-semibold">No me des un tema. Déjame encontrarlo.</h2><p className="mt-3 text-sm leading-6 text-white/60">Cruzo tu marca, lo que ya publicaste y las señales de rendimiento para abrir seis caminos distintos.</p></div><form action={action}><button className="inline-flex min-h-44 min-w-44 flex-col items-center justify-center rounded-full bg-[var(--mint)] p-6 text-center font-black text-[var(--ink)] transition hover:scale-[1.02] disabled:opacity-60" disabled={pending}><Sparkles size={24}/><span className="mt-2">{pending?"Pensando…":state.ideas.length?"Generar más ideas":"Buscar ideas"}</span></button></form></div>{state.message&&<p className={`border-t border-white/10 px-6 py-3 text-sm sm:px-8 ${state.ok?"text-white/70":"text-red-200"}`}>{state.message}</p>}{state.ideas.length>0&&<div className="grid gap-px bg-white/10 md:grid-cols-2">{state.ideas.map((idea,index)=><IdeaCard idea={idea} index={index} key={idea.id}/>)}</div>}</section>}
function IdeaCard({idea,index}:{idea:ProposedIdea;index:number}){const[state,action]=useActionState(chooseIdea,{ok:false,message:""} satisfies ChooseIdeaState);return <article className="bg-[var(--ink)] p-6 sm:p-7"><div className="flex items-center justify-between"><span className="text-[10px] font-black text-[var(--mint)]">{String(index+1).padStart(2,"0")} · {idea.format}</span><span className="text-[10px] text-white/40">Novedad {Math.round(idea.noveltyScore*100)}%</span></div><h3 className="editorial-title mt-4 text-2xl font-semibold">{idea.hook}</h3><p className="mt-3 text-sm leading-6 text-white/60">{idea.concept}</p><p className="mt-4 text-xs leading-5 text-white/40">{idea.strategyReason}</p><form action={action} className="mt-5"><input type="hidden" name="ideaId" value={idea.id}/><ChooseButton queued={state.ok}/></form>{state.message&&<p className={`mt-3 text-xs ${state.ok?"text-[var(--mint)]":"text-red-200"}`}>{state.message}</p>}</article>}
function ChooseButton({queued}:{queued:boolean}){const{pending}=useFormStatus();return <button className="inline-flex items-center gap-2 text-sm font-black text-[var(--mint)] disabled:opacity-50" disabled={pending||queued}>{pending?"Encolando…":queued?"En cola":"Enviar a la cola"}<ArrowRight size={15}/></button>}
