import "server-only";
import {createSupabaseServerClient} from "@/lib/supabase/server";

async function signed(db:Awaited<ReturnType<typeof createSupabaseServerClient>>,asset:unknown){const row=(Array.isArray(asset)?asset[0]:asset) as {bucket?:string;object_key?:string}|null;if(!row?.bucket||!row.object_key)return null;const{data}=await db.storage.from(row.bucket).createSignedUrl(row.object_key,3600);return data?.signedUrl??null;}
function panamaDay(dayOffset=0){const now=new Date(Date.now()+dayOffset*86_400_000);const date=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Panama",year:"numeric",month:"2-digit",day:"2-digit"}).format(now);return{start:new Date(`${date}T00:00:00-05:00`),end:new Date(`${date}T23:59:59.999-05:00`),label:new Intl.DateTimeFormat("es-PA",{timeZone:"America/Panama",weekday:"long"}).format(now)};}

export async function getOverviewData(){const db=await createSupabaseServerClient();const{data:auth}=await db.auth.getUser();if(!auth.user)return null;const{data:brand}=await db.from("brands").select("id,name").eq("owner_user_id",auth.user.id).limit(1).maybeSingle();if(!brand)return{brand:null};const today=panamaDay();const[{count:scheduled},{count:approvals},{count:published},{data:next},{data:future}]=await Promise.all([db.from("posts").select("id",{count:"exact",head:true}).eq("brand_id",brand.id).gte("scheduled_at",today.start.toISOString()).lte("scheduled_at",today.end.toISOString()).in("status",["APPROVED","SCHEDULED","PUBLISHING"]),db.from("posts").select("id",{count:"exact",head:true}).eq("brand_id",brand.id).in("status",["PENDING_APPROVAL","NEEDS_CHANGES"]),db.from("posts").select("id",{count:"exact",head:true}).eq("brand_id",brand.id).gte("published_at",today.start.toISOString()).lte("published_at",today.end.toISOString()).eq("status","PUBLISHED"),db.from("posts").select("id,format,status,scheduled_at,media_assets!posts_cover_media_asset_id_fkey(bucket,object_key),post_versions!posts_current_version_id_fkey(hook)").eq("brand_id",brand.id).gte("scheduled_at",new Date().toISOString()).in("status",["APPROVED","SCHEDULED","PUBLISHING"]).order("scheduled_at").limit(1).maybeSingle(),db.from("posts").select("scheduled_at,status").eq("brand_id",brand.id).gte("scheduled_at",new Date().toISOString()).lte("scheduled_at",panamaDay(5).end.toISOString()).not("status","in",'(REJECTED,FAILED)')]);const days=Array.from({length:5},(_,index)=>{const day=panamaDay(index);return{label:index===0?"Hoy":day.label,count:(future??[]).filter(post=>{const at=new Date(post.scheduled_at);return at>=day.start&&at<=day.end;}).length};});const version=next&&(Array.isArray(next.post_versions)?next.post_versions[0]:next.post_versions);return{brand,scheduled:scheduled??0,approvals:approvals??0,published:published??0,next:next?{id:next.id,format:next.format,status:next.status,scheduledAt:next.scheduled_at,hook:version?.hook??"Próxima publicación",coverUrl:await signed(db,next.media_assets)}:null,days};}

export async function getLibraryData(){const db=await createSupabaseServerClient();const{data:auth}=await db.auth.getUser();if(!auth.user)return[];const{data,error}=await db.from("posts").select("id,format,status,created_at,published_at,scheduled_at,current_version_id,content_ideas(topic),media_assets!posts_cover_media_asset_id_fkey(bucket,object_key,width,height),post_versions!post_versions_post_id_fkey(id,version_number,hook,caption,created_at),carousels(carousel_slides(position,headline,media_assets(bucket,object_key)))").not("cover_media_asset_id","is",null).order("created_at",{ascending:false}).limit(60);if(error)throw new Error(`No se pudo cargar la Biblioteca: ${error.message}`);return Promise.all((data??[]).map(async post=>{const versions=(post.post_versions??[]).sort((a,b)=>b.version_number-a.version_number);const current=versions.find(v=>v.id===post.current_version_id)??versions[0];const idea=Array.isArray(post.content_ideas)?post.content_ideas[0]:post.content_ideas;const carousel=Array.isArray(post.carousels)?post.carousels[0]:post.carousels;const slides=await Promise.all((carousel?.carousel_slides??[]).sort((a,b)=>a.position-b.position).map(async slide=>({position:slide.position,headline:slide.headline,imageUrl:await signed(db,slide.media_assets)})));const imageUrl=await signed(db,post.media_assets);return{id:post.id,format:post.format,status:post.status,createdAt:post.created_at,publishedAt:post.published_at,scheduledAt:post.scheduled_at,topic:idea?.topic??"Contenido",hook:current?.hook??"Sin titular",caption:current?.caption??"",versions:versions.length,imageUrl,slides:slides.length?slides:[{position:1,headline:current?.hook??"Contenido",imageUrl}]};}));}
