"use server";
import {revalidatePath} from "next/cache";
import {z} from "zod";
import {createSupabaseServerClient} from "@/lib/supabase/server";

const id=z.string().uuid();const text=z.string().trim().min(3).max(2000);
async function context(postId:string){const client=await createSupabaseServerClient();const{data:auth}=await client.auth.getUser();if(!auth.user)throw new Error("Sesión expirada");const{data:post}=await client.from("posts").select("id,status,current_version_id,post_versions(*)").eq("id",id.parse(postId)).single();if(!post)throw new Error("Contenido no disponible");return{client,user:auth.user,post}}
function refresh(){revalidatePath("/approvals");revalidatePath("/calendar");revalidatePath("/overview")}
async function saveSchedule(client:Awaited<ReturnType<typeof createSupabaseServerClient>>,postId:string,at:Date){const values={scheduled_at:at.toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,active:true};const{data:existing}=await client.from("schedules").select("id,revision").eq("post_id",postId).eq("active",true).maybeSingle();if(existing)await client.from("schedules").update({...values,revision:existing.revision+1}).eq("id",existing.id).throwOnError();else await client.from("schedules").insert({post_id:postId,...values}).throwOnError()}
export async function approvePost(postId:string,formData:FormData){const{client}=await context(postId);const raw=String(formData.get("scheduledAt")??"");let at:Date|null=null;if(raw){at=new Date(raw);if(Number.isNaN(at.valueOf())||at<=new Date())throw new Error("Elige una fecha futura")}await client.rpc("apply_editorial_transition",{target_post_id:postId,next_status:at?"SCHEDULED":"APPROVED",event_note:at?"Aprobado y programado":"Aprobado"}).throwOnError();if(at){await saveSchedule(client,postId,at);await client.from("posts").update({scheduled_at:at.toISOString()}).eq("id",postId).throwOnError()}refresh()}
export async function rejectPost(postId:string){const{client}=await context(postId);await client.rpc("apply_editorial_transition",{target_post_id:postId,next_status:"REJECTED",event_note:"Rechazado en revisión"}).throwOnError();refresh()}
export async function requestChanges(postId:string,formData:FormData){const feedback=text.parse(formData.get("feedback"));const{client,user,post}=await context(postId);const versions=(post.post_versions as Record<string,unknown>[]).sort((a,b)=>Number(b.version_number)-Number(a.version_number));const source=versions.find(v=>v.id===post.current_version_id)??versions[0];if(!source)throw new Error("No existe una versión para revisar");const next=Number(versions[0]?.version_number??0)+1;const{data:version,error}=await client.from("post_versions").insert({post_id:postId,version_number:next,hook:source.hook,caption:source.caption,cta:source.cta,alt_text:source.alt_text,hashtags:source.hashtags,visual_direction:source.visual_direction,source_version_id:source.id,change_reason:feedback,created_by_kind:"USER"}).select("id").single();if(error)throw error;await client.from("revision_requests").insert({post_id:postId,source_version_id:source.id,result_version_id:version.id,feedback,status:"RESOLVED",created_by:user.id,resolved_at:new Date().toISOString()}).throwOnError();await client.from("posts").update({current_version_id:version.id}).eq("id",postId).throwOnError();await client.rpc("apply_editorial_transition",{target_post_id:postId,next_status:"NEEDS_CHANGES",event_note:feedback}).throwOnError();refresh()}
export async function editPostCopy(postId:string,formData:FormData){const hook=text.parse(formData.get("hook"));const caption=text.parse(formData.get("caption"));const{client,post}=await context(postId);const versions=(post.post_versions as Record<string,unknown>[]).sort((a,b)=>Number(b.version_number)-Number(a.version_number));const source=versions.find(v=>v.id===post.current_version_id)??versions[0];const{data,error}=await client.from("post_versions").insert({post_id:postId,version_number:Number(versions[0]?.version_number??0)+1,hook,caption,cta:source.cta,alt_text:source.alt_text,hashtags:source.hashtags,visual_direction:source.visual_direction,source_version_id:source.id,change_reason:"Edición editorial manual",created_by_kind:"USER"}).select("id").single();if(error)throw error;await client.from("posts").update({current_version_id:data.id}).eq("id",postId).throwOnError();refresh()}
export async function moveSchedule(postId:string,iso:string){const at=new Date(iso);if(Number.isNaN(at.valueOf())||at<=new Date())throw new Error("La fecha debe ser futura");const{client,post}=await context(postId);if(!["APPROVED","SCHEDULED"].includes(post.status))throw new Error("Solo se programa contenido aprobado");await saveSchedule(client,postId,at);await client.from("posts").update({scheduled_at:at.toISOString()}).eq("id",postId).throwOnError();if(post.status==="APPROVED")await client.rpc("apply_editorial_transition",{target_post_id:postId,next_status:"SCHEDULED",event_note:"Programado desde calendario"}).throwOnError();refresh()}
